package com.blist.metrics.impl.queue;

import com.socrata.balboa.metrics.Metrics;

/**
 * Immutable class that represents a bag of metrics that relates to a specific entity id
 * and timeBucket.  A bag of metrics unlike {@link Metrics}, is associated directly to a name
 * and a time bucket.
 *
 * @see Metrics
 *
 * Created by michaelhotan on 1/29/16.
 */
public class MetricsBag {

    /*
    Developer Notes:
    * TODO This class probably belongs in balboa-common
     */
    private final Metrics data;
    private final long timeBucket;
    private final String id;

    /**
     * Creates a Metrics Bag.
     *
     * @param id The id to associate data to.
     * @param data The actual {@link Metrics} data.
     * @param timeBucket The bucket that data is associated to.
     */
    MetricsBag(String id, Metrics data, long timeBucket) {
        // TODO A little bit dangerous to assume the client will understand the timeBucket will actually
        this.id = id;
        this.data = data;
        this.timeBucket = timeBucket;
    }


    /**
     * Time complexity: O(n)
     *
     * @return A copy of the internal metrics data.
     */
    public Metrics getData() {
        // DEV NOTES: We sacrifice performance gains of returning a reference to the underlying data structure for
        // maintainability and preserving the immutable data structure model.
        // This was a design choice that was deemed appropriate because this Class is not meant to be on any
        // code path optimized for time.
        return new Metrics(data);
    }

    /**
     * @return The time bucket this metrics fall under.
     */
    public long getTimeBucket() {
        return timeBucket;
    }

    /**
     * @return The id of the Metric Bag
     */
    public String getId() {
        return id;
    }

    @Override
    public String toString() {
        return "MetricsBag{" +
                "timeBucket=" + timeBucket +
                ", id='" + id + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        // Generated by Idea Intellij
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        MetricsBag item = (MetricsBag) o;
        if (timeBucket != item.timeBucket) return false;
        return id.equals(item.id);
    }

    @Override
    public int hashCode() {
        // Generated by Idea Intellij
        int result = (int) (timeBucket ^ (timeBucket >>> 32));
        result = 31 * result + id.hashCode();
        return result;
    }


}
