#! /bin/bash
#
# This script is the entry point to execute all the integration tests for this
# repository. It is executed by a Jenkins job on each pull request.
#

# The balboa-agent integration tests exist but don't yet have the necessary
# functionality to start up ActiveMQ, so for the moment they are removed from
# this script, which is run by Jenkins as part of every pull request.
# Right now the `balboa-agent` integration tests, when executed on Jenkins,
# hang looking for the ActiveMQ server to remove the queue from during clean
# up. As an emergency step, I'm disabling those tests for the moment.
#balboa-agent/src/it/bash/integration-tests
balboa-http/src/it/bash/integration-tests
