#! /bin/bash

# Right now the `balboa-agent` integration tests, when executed on Jenkins,
# hang looking for the ActiveMQ server to remove the queue from during clean
# up. As an emergency step, I'm disabling those tests for the moment.
#balboa-agent/src/it/bash/integration-tests
balboa-http/src/it/bash/integration-tests
