// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: numbers.proto

package com.socrata.balboa.metrics.measurements.serialization.impl;

public final class NumbersProtos {
  private NumbersProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PBNumber extends
      com.google.protobuf.GeneratedMessage {
    // Use PBNumber.newBuilder() to construct.
    private PBNumber() {
      initFields();
    }
    private PBNumber(boolean noInit) {}
    
    private static final PBNumber defaultInstance;
    public static PBNumber getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBNumber getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.internal_static_com_socrata_balboa_PBNumber_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.internal_static_com_socrata_balboa_PBNumber_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      INT(0, 1),
      DOUBLE(1, 2),
      LONG(2, 3),
      BIG_DECIMAL(3, 4),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return INT;
          case 2: return DOUBLE;
          case 3: return LONG;
          case 4: return BIG_DECIMAL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        INT, DOUBLE, LONG, BIG_DECIMAL, 
      };
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:com.socrata.balboa.PBNumber.Type)
    }
    
    // required .com.socrata.balboa.PBNumber.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.Type type_;
    public boolean hasType() { return hasType; }
    public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.Type getType() { return type_; }
    
    // optional int32 int_value = 2;
    public static final int INT_VALUE_FIELD_NUMBER = 2;
    private boolean hasIntValue;
    private int intValue_ = 0;
    public boolean hasIntValue() { return hasIntValue; }
    public int getIntValue() { return intValue_; }
    
    // optional double double_value = 3;
    public static final int DOUBLE_VALUE_FIELD_NUMBER = 3;
    private boolean hasDoubleValue;
    private double doubleValue_ = 0D;
    public boolean hasDoubleValue() { return hasDoubleValue; }
    public double getDoubleValue() { return doubleValue_; }
    
    // optional int64 long_value = 4;
    public static final int LONG_VALUE_FIELD_NUMBER = 4;
    private boolean hasLongValue;
    private long longValue_ = 0L;
    public boolean hasLongValue() { return hasLongValue; }
    public long getLongValue() { return longValue_; }
    
    // optional .com.socrata.balboa.PBBigDecimal big_decimal_value = 5;
    public static final int BIG_DECIMAL_VALUE_FIELD_NUMBER = 5;
    private boolean hasBigDecimalValue;
    private com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal bigDecimalValue_;
    public boolean hasBigDecimalValue() { return hasBigDecimalValue; }
    public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal getBigDecimalValue() { return bigDecimalValue_; }
    
    private void initFields() {
      type_ = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.Type.INT;
      bigDecimalValue_ = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasType) return false;
      if (hasBigDecimalValue()) {
        if (!getBigDecimalValue().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
      if (hasIntValue()) {
        output.writeInt32(2, getIntValue());
      }
      if (hasDoubleValue()) {
        output.writeDouble(3, getDoubleValue());
      }
      if (hasLongValue()) {
        output.writeInt64(4, getLongValue());
      }
      if (hasBigDecimalValue()) {
        output.writeMessage(5, getBigDecimalValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      if (hasIntValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getIntValue());
      }
      if (hasDoubleValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, getDoubleValue());
      }
      if (hasLongValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, getLongValue());
      }
      if (hasBigDecimalValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getBigDecimalValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber result;
      
      // Construct using com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber();
        return builder;
      }
      
      protected com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.getDescriptor();
      }
      
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber getDefaultInstanceForType() {
        return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber) {
          return mergeFrom((com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber other) {
        if (other == com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasIntValue()) {
          setIntValue(other.getIntValue());
        }
        if (other.hasDoubleValue()) {
          setDoubleValue(other.getDoubleValue());
        }
        if (other.hasLongValue()) {
          setLongValue(other.getLongValue());
        }
        if (other.hasBigDecimalValue()) {
          mergeBigDecimalValue(other.getBigDecimalValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.Type value = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 16: {
              setIntValue(input.readInt32());
              break;
            }
            case 25: {
              setDoubleValue(input.readDouble());
              break;
            }
            case 32: {
              setLongValue(input.readInt64());
              break;
            }
            case 42: {
              com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.Builder subBuilder = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.newBuilder();
              if (hasBigDecimalValue()) {
                subBuilder.mergeFrom(getBigDecimalValue());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBigDecimalValue(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .com.socrata.balboa.PBNumber.Type type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.Type getType() {
        return result.getType();
      }
      public Builder setType(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.Type.INT;
        return this;
      }
      
      // optional int32 int_value = 2;
      public boolean hasIntValue() {
        return result.hasIntValue();
      }
      public int getIntValue() {
        return result.getIntValue();
      }
      public Builder setIntValue(int value) {
        result.hasIntValue = true;
        result.intValue_ = value;
        return this;
      }
      public Builder clearIntValue() {
        result.hasIntValue = false;
        result.intValue_ = 0;
        return this;
      }
      
      // optional double double_value = 3;
      public boolean hasDoubleValue() {
        return result.hasDoubleValue();
      }
      public double getDoubleValue() {
        return result.getDoubleValue();
      }
      public Builder setDoubleValue(double value) {
        result.hasDoubleValue = true;
        result.doubleValue_ = value;
        return this;
      }
      public Builder clearDoubleValue() {
        result.hasDoubleValue = false;
        result.doubleValue_ = 0D;
        return this;
      }
      
      // optional int64 long_value = 4;
      public boolean hasLongValue() {
        return result.hasLongValue();
      }
      public long getLongValue() {
        return result.getLongValue();
      }
      public Builder setLongValue(long value) {
        result.hasLongValue = true;
        result.longValue_ = value;
        return this;
      }
      public Builder clearLongValue() {
        result.hasLongValue = false;
        result.longValue_ = 0L;
        return this;
      }
      
      // optional .com.socrata.balboa.PBBigDecimal big_decimal_value = 5;
      public boolean hasBigDecimalValue() {
        return result.hasBigDecimalValue();
      }
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal getBigDecimalValue() {
        return result.getBigDecimalValue();
      }
      public Builder setBigDecimalValue(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasBigDecimalValue = true;
        result.bigDecimalValue_ = value;
        return this;
      }
      public Builder setBigDecimalValue(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.Builder builderForValue) {
        result.hasBigDecimalValue = true;
        result.bigDecimalValue_ = builderForValue.build();
        return this;
      }
      public Builder mergeBigDecimalValue(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal value) {
        if (result.hasBigDecimalValue() &&
            result.bigDecimalValue_ != com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.getDefaultInstance()) {
          result.bigDecimalValue_ =
            com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.newBuilder(result.bigDecimalValue_).mergeFrom(value).buildPartial();
        } else {
          result.bigDecimalValue_ = value;
        }
        result.hasBigDecimalValue = true;
        return this;
      }
      public Builder clearBigDecimalValue() {
        result.hasBigDecimalValue = false;
        result.bigDecimalValue_ = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socrata.balboa.PBNumber)
    }
    
    static {
      defaultInstance = new PBNumber(true);
      com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socrata.balboa.PBNumber)
  }
  
  public static final class PBBigDecimal extends
      com.google.protobuf.GeneratedMessage {
    // Use PBBigDecimal.newBuilder() to construct.
    private PBBigDecimal() {
      initFields();
    }
    private PBBigDecimal(boolean noInit) {}
    
    private static final PBBigDecimal defaultInstance;
    public static PBBigDecimal getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBBigDecimal getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.internal_static_com_socrata_balboa_PBBigDecimal_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.internal_static_com_socrata_balboa_PBBigDecimal_fieldAccessorTable;
    }
    
    // required int32 scale = 1;
    public static final int SCALE_FIELD_NUMBER = 1;
    private boolean hasScale;
    private int scale_ = 0;
    public boolean hasScale() { return hasScale; }
    public int getScale() { return scale_; }
    
    // required .com.socrata.balboa.PBBigInteger value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private boolean hasValue;
    private com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger value_;
    public boolean hasValue() { return hasValue; }
    public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger getValue() { return value_; }
    
    private void initFields() {
      value_ = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasScale) return false;
      if (!hasValue) return false;
      if (!getValue().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasScale()) {
        output.writeInt32(1, getScale());
      }
      if (hasValue()) {
        output.writeMessage(2, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasScale()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getScale());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal result;
      
      // Construct using com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal();
        return builder;
      }
      
      protected com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.getDescriptor();
      }
      
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal getDefaultInstanceForType() {
        return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal) {
          return mergeFrom((com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal other) {
        if (other == com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.getDefaultInstance()) return this;
        if (other.hasScale()) {
          setScale(other.getScale());
        }
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setScale(input.readInt32());
              break;
            }
            case 18: {
              com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.Builder subBuilder = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.newBuilder();
              if (hasValue()) {
                subBuilder.mergeFrom(getValue());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setValue(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 scale = 1;
      public boolean hasScale() {
        return result.hasScale();
      }
      public int getScale() {
        return result.getScale();
      }
      public Builder setScale(int value) {
        result.hasScale = true;
        result.scale_ = value;
        return this;
      }
      public Builder clearScale() {
        result.hasScale = false;
        result.scale_ = 0;
        return this;
      }
      
      // required .com.socrata.balboa.PBBigInteger value = 2;
      public boolean hasValue() {
        return result.hasValue();
      }
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger getValue() {
        return result.getValue();
      }
      public Builder setValue(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder setValue(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.Builder builderForValue) {
        result.hasValue = true;
        result.value_ = builderForValue.build();
        return this;
      }
      public Builder mergeValue(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger value) {
        if (result.hasValue() &&
            result.value_ != com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.getDefaultInstance()) {
          result.value_ =
            com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.newBuilder(result.value_).mergeFrom(value).buildPartial();
        } else {
          result.value_ = value;
        }
        result.hasValue = true;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socrata.balboa.PBBigDecimal)
    }
    
    static {
      defaultInstance = new PBBigDecimal(true);
      com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socrata.balboa.PBBigDecimal)
  }
  
  public static final class PBBigInteger extends
      com.google.protobuf.GeneratedMessage {
    // Use PBBigInteger.newBuilder() to construct.
    private PBBigInteger() {
      initFields();
    }
    private PBBigInteger(boolean noInit) {}
    
    private static final PBBigInteger defaultInstance;
    public static PBBigInteger getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBBigInteger getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.internal_static_com_socrata_balboa_PBBigInteger_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.internal_static_com_socrata_balboa_PBBigInteger_fieldAccessorTable;
    }
    
    // required bytes value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private boolean hasValue;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasValue() { return hasValue; }
    public com.google.protobuf.ByteString getValue() { return value_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasValue) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasValue()) {
        output.writeBytes(1, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger result;
      
      // Construct using com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger();
        return builder;
      }
      
      protected com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.getDescriptor();
      }
      
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger getDefaultInstanceForType() {
        return com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger) {
          return mergeFrom((com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger other) {
        if (other == com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setValue(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required bytes value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public com.google.protobuf.ByteString getValue() {
        return result.getValue();
      }
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = getDefaultInstance().getValue();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socrata.balboa.PBBigInteger)
    }
    
    static {
      defaultInstance = new PBBigInteger(true);
      com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socrata.balboa.PBBigInteger)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socrata_balboa_PBNumber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socrata_balboa_PBNumber_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socrata_balboa_PBBigDecimal_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socrata_balboa_PBBigDecimal_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socrata_balboa_PBBigInteger_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socrata_balboa_PBBigInteger_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rnumbers.proto\022\022com.socrata.balboa\"\355\001\n\010" +
      "PBNumber\022/\n\004type\030\001 \002(\0162!.com.socrata.bal" +
      "boa.PBNumber.Type\022\021\n\tint_value\030\002 \001(\005\022\024\n\014" +
      "double_value\030\003 \001(\001\022\022\n\nlong_value\030\004 \001(\003\022;" +
      "\n\021big_decimal_value\030\005 \001(\0132 .com.socrata." +
      "balboa.PBBigDecimal\"6\n\004Type\022\007\n\003INT\020\001\022\n\n\006" +
      "DOUBLE\020\002\022\010\n\004LONG\020\003\022\017\n\013BIG_DECIMAL\020\004\"N\n\014P" +
      "BBigDecimal\022\r\n\005scale\030\001 \002(\005\022/\n\005value\030\002 \002(" +
      "\0132 .com.socrata.balboa.PBBigInteger\"\035\n\014P" +
      "BBigInteger\022\r\n\005value\030\001 \002(\014BK\n:com.socrat",
      "a.balboa.metrics.measurements.serializat" +
      "ion.implB\rNumbersProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_socrata_balboa_PBNumber_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_socrata_balboa_PBNumber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socrata_balboa_PBNumber_descriptor,
              new java.lang.String[] { "Type", "IntValue", "DoubleValue", "LongValue", "BigDecimalValue", },
              com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.class,
              com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.Builder.class);
          internal_static_com_socrata_balboa_PBBigDecimal_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_socrata_balboa_PBBigDecimal_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socrata_balboa_PBBigDecimal_descriptor,
              new java.lang.String[] { "Scale", "Value", },
              com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.class,
              com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigDecimal.Builder.class);
          internal_static_com_socrata_balboa_PBBigInteger_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_socrata_balboa_PBBigInteger_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socrata_balboa_PBBigInteger_descriptor,
              new java.lang.String[] { "Value", },
              com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.class,
              com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBBigInteger.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
