// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.socrata.balboa.metrics.impl;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PBMessages extends
      com.google.protobuf.GeneratedMessage {
    // Use PBMessages.newBuilder() to construct.
    private PBMessages() {
      initFields();
    }
    private PBMessages(boolean noInit) {}
    
    private static final PBMessages defaultInstance;
    public static PBMessages getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBMessages getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socrata.balboa.metrics.impl.MessageProtos.internal_static_com_socrata_balboa_PBMessages_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socrata.balboa.metrics.impl.MessageProtos.internal_static_com_socrata_balboa_PBMessages_fieldAccessorTable;
    }
    
    // repeated .com.socrata.balboa.PBMessage messages = 1;
    public static final int MESSAGES_FIELD_NUMBER = 1;
    private java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMessage> messages_ =
      java.util.Collections.emptyList();
    public java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMessage> getMessagesList() {
      return messages_;
    }
    public int getMessagesCount() { return messages_.size(); }
    public com.socrata.balboa.metrics.impl.MessageProtos.PBMessage getMessages(int index) {
      return messages_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMessage element : getMessagesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMessage element : getMessagesList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMessage element : getMessagesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socrata.balboa.metrics.impl.MessageProtos.PBMessages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.socrata.balboa.metrics.impl.MessageProtos.PBMessages result;
      
      // Construct using com.socrata.balboa.metrics.impl.MessageProtos.PBMessages.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.socrata.balboa.metrics.impl.MessageProtos.PBMessages();
        return builder;
      }
      
      protected com.socrata.balboa.metrics.impl.MessageProtos.PBMessages internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.socrata.balboa.metrics.impl.MessageProtos.PBMessages();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMessages.getDescriptor();
      }
      
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMessages getDefaultInstanceForType() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMessages.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMessages build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.socrata.balboa.metrics.impl.MessageProtos.PBMessages buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMessages buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.messages_ != java.util.Collections.EMPTY_LIST) {
          result.messages_ =
            java.util.Collections.unmodifiableList(result.messages_);
        }
        com.socrata.balboa.metrics.impl.MessageProtos.PBMessages returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socrata.balboa.metrics.impl.MessageProtos.PBMessages) {
          return mergeFrom((com.socrata.balboa.metrics.impl.MessageProtos.PBMessages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socrata.balboa.metrics.impl.MessageProtos.PBMessages other) {
        if (other == com.socrata.balboa.metrics.impl.MessageProtos.PBMessages.getDefaultInstance()) return this;
        if (!other.messages_.isEmpty()) {
          if (result.messages_.isEmpty()) {
            result.messages_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMessage>();
          }
          result.messages_.addAll(other.messages_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Builder subBuilder = com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMessages(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.socrata.balboa.PBMessage messages = 1;
      public java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMessage> getMessagesList() {
        return java.util.Collections.unmodifiableList(result.messages_);
      }
      public int getMessagesCount() {
        return result.getMessagesCount();
      }
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMessage getMessages(int index) {
        return result.getMessages(index);
      }
      public Builder setMessages(int index, com.socrata.balboa.metrics.impl.MessageProtos.PBMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.messages_.set(index, value);
        return this;
      }
      public Builder setMessages(int index, com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Builder builderForValue) {
        result.messages_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMessages(com.socrata.balboa.metrics.impl.MessageProtos.PBMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.messages_.isEmpty()) {
          result.messages_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMessage>();
        }
        result.messages_.add(value);
        return this;
      }
      public Builder addMessages(com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Builder builderForValue) {
        if (result.messages_.isEmpty()) {
          result.messages_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMessage>();
        }
        result.messages_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMessages(
          java.lang.Iterable<? extends com.socrata.balboa.metrics.impl.MessageProtos.PBMessage> values) {
        if (result.messages_.isEmpty()) {
          result.messages_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMessage>();
        }
        super.addAll(values, result.messages_);
        return this;
      }
      public Builder clearMessages() {
        result.messages_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socrata.balboa.PBMessages)
    }
    
    static {
      defaultInstance = new PBMessages(true);
      com.socrata.balboa.metrics.impl.MessageProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socrata.balboa.PBMessages)
  }
  
  public static final class PBMetricsSeries extends
      com.google.protobuf.GeneratedMessage {
    // Use PBMetricsSeries.newBuilder() to construct.
    private PBMetricsSeries() {
      initFields();
    }
    private PBMetricsSeries(boolean noInit) {}
    
    private static final PBMetricsSeries defaultInstance;
    public static PBMetricsSeries getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBMetricsSeries getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socrata.balboa.metrics.impl.MessageProtos.internal_static_com_socrata_balboa_PBMetricsSeries_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socrata.balboa.metrics.impl.MessageProtos.internal_static_com_socrata_balboa_PBMetricsSeries_fieldAccessorTable;
    }
    
    // repeated .com.socrata.balboa.PBMetrics series = 1;
    public static final int SERIES_FIELD_NUMBER = 1;
    private java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics> series_ =
      java.util.Collections.emptyList();
    public java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics> getSeriesList() {
      return series_;
    }
    public int getSeriesCount() { return series_.size(); }
    public com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics getSeries(int index) {
      return series_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics element : getSeriesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics element : getSeriesList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics element : getSeriesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries result;
      
      // Construct using com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries();
        return builder;
      }
      
      protected com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries.getDescriptor();
      }
      
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries getDefaultInstanceForType() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.series_ != java.util.Collections.EMPTY_LIST) {
          result.series_ =
            java.util.Collections.unmodifiableList(result.series_);
        }
        com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries) {
          return mergeFrom((com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries other) {
        if (other == com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries.getDefaultInstance()) return this;
        if (!other.series_.isEmpty()) {
          if (result.series_.isEmpty()) {
            result.series_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics>();
          }
          result.series_.addAll(other.series_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics.Builder subBuilder = com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSeries(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.socrata.balboa.PBMetrics series = 1;
      public java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics> getSeriesList() {
        return java.util.Collections.unmodifiableList(result.series_);
      }
      public int getSeriesCount() {
        return result.getSeriesCount();
      }
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics getSeries(int index) {
        return result.getSeries(index);
      }
      public Builder setSeries(int index, com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.series_.set(index, value);
        return this;
      }
      public Builder setSeries(int index, com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics.Builder builderForValue) {
        result.series_.set(index, builderForValue.build());
        return this;
      }
      public Builder addSeries(com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.series_.isEmpty()) {
          result.series_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics>();
        }
        result.series_.add(value);
        return this;
      }
      public Builder addSeries(com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics.Builder builderForValue) {
        if (result.series_.isEmpty()) {
          result.series_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics>();
        }
        result.series_.add(builderForValue.build());
        return this;
      }
      public Builder addAllSeries(
          java.lang.Iterable<? extends com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics> values) {
        if (result.series_.isEmpty()) {
          result.series_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics>();
        }
        super.addAll(values, result.series_);
        return this;
      }
      public Builder clearSeries() {
        result.series_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socrata.balboa.PBMetricsSeries)
    }
    
    static {
      defaultInstance = new PBMetricsSeries(true);
      com.socrata.balboa.metrics.impl.MessageProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socrata.balboa.PBMetricsSeries)
  }
  
  public static final class PBMetrics extends
      com.google.protobuf.GeneratedMessage {
    // Use PBMetrics.newBuilder() to construct.
    private PBMetrics() {
      initFields();
    }
    private PBMetrics(boolean noInit) {}
    
    private static final PBMetrics defaultInstance;
    public static PBMetrics getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBMetrics getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socrata.balboa.metrics.impl.MessageProtos.internal_static_com_socrata_balboa_PBMetrics_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socrata.balboa.metrics.impl.MessageProtos.internal_static_com_socrata_balboa_PBMetrics_fieldAccessorTable;
    }
    
    // repeated .com.socrata.balboa.PBMetric metrics = 1;
    public static final int METRICS_FIELD_NUMBER = 1;
    private java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric> metrics_ =
      java.util.Collections.emptyList();
    public java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric> getMetricsList() {
      return metrics_;
    }
    public int getMetricsCount() { return metrics_.size(); }
    public com.socrata.balboa.metrics.impl.MessageProtos.PBMetric getMetrics(int index) {
      return metrics_.get(index);
    }
    
    // optional int64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMetric element : getMetricsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMetric element : getMetricsList()) {
        output.writeMessage(1, element);
      }
      if (hasTimestamp()) {
        output.writeInt64(2, getTimestamp());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMetric element : getMetricsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getTimestamp());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics result;
      
      // Construct using com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics();
        return builder;
      }
      
      protected com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics.getDescriptor();
      }
      
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics getDefaultInstanceForType() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.metrics_ != java.util.Collections.EMPTY_LIST) {
          result.metrics_ =
            java.util.Collections.unmodifiableList(result.metrics_);
        }
        com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics) {
          return mergeFrom((com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics other) {
        if (other == com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics.getDefaultInstance()) return this;
        if (!other.metrics_.isEmpty()) {
          if (result.metrics_.isEmpty()) {
            result.metrics_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric>();
          }
          result.metrics_.addAll(other.metrics_);
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Builder subBuilder = com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMetrics(subBuilder.buildPartial());
              break;
            }
            case 16: {
              setTimestamp(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.socrata.balboa.PBMetric metrics = 1;
      public java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric> getMetricsList() {
        return java.util.Collections.unmodifiableList(result.metrics_);
      }
      public int getMetricsCount() {
        return result.getMetricsCount();
      }
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetric getMetrics(int index) {
        return result.getMetrics(index);
      }
      public Builder setMetrics(int index, com.socrata.balboa.metrics.impl.MessageProtos.PBMetric value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.metrics_.set(index, value);
        return this;
      }
      public Builder setMetrics(int index, com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Builder builderForValue) {
        result.metrics_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMetrics(com.socrata.balboa.metrics.impl.MessageProtos.PBMetric value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.metrics_.isEmpty()) {
          result.metrics_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric>();
        }
        result.metrics_.add(value);
        return this;
      }
      public Builder addMetrics(com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Builder builderForValue) {
        if (result.metrics_.isEmpty()) {
          result.metrics_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric>();
        }
        result.metrics_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMetrics(
          java.lang.Iterable<? extends com.socrata.balboa.metrics.impl.MessageProtos.PBMetric> values) {
        if (result.metrics_.isEmpty()) {
          result.metrics_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric>();
        }
        super.addAll(values, result.metrics_);
        return this;
      }
      public Builder clearMetrics() {
        result.metrics_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional int64 timestamp = 2;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socrata.balboa.PBMetrics)
    }
    
    static {
      defaultInstance = new PBMetrics(true);
      com.socrata.balboa.metrics.impl.MessageProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socrata.balboa.PBMetrics)
  }
  
  public static final class PBMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use PBMessage.newBuilder() to construct.
    private PBMessage() {
      initFields();
    }
    private PBMessage(boolean noInit) {}
    
    private static final PBMessage defaultInstance;
    public static PBMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socrata.balboa.metrics.impl.MessageProtos.internal_static_com_socrata_balboa_PBMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socrata.balboa.metrics.impl.MessageProtos.internal_static_com_socrata_balboa_PBMessage_fieldAccessorTable;
    }
    
    public enum Version
        implements com.google.protobuf.ProtocolMessageEnum {
      V1_0(0, 0),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Version valueOf(int value) {
        switch (value) {
          case 0: return V1_0;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Version>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Version>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Version>() {
              public Version findValueByNumber(int number) {
                return Version.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Version[] VALUES = {
        V1_0, 
      };
      public static Version valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Version(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.socrata.balboa.metrics.impl.MessageProtos.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:com.socrata.balboa.PBMessage.Version)
    }
    
    // required string entity_id = 1;
    public static final int ENTITY_ID_FIELD_NUMBER = 1;
    private boolean hasEntityId;
    private java.lang.String entityId_ = "";
    public boolean hasEntityId() { return hasEntityId; }
    public java.lang.String getEntityId() { return entityId_; }
    
    // required .com.socrata.balboa.PBMessage.Version version = 2;
    public static final int VERSION_FIELD_NUMBER = 2;
    private boolean hasVersion;
    private com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Version version_;
    public boolean hasVersion() { return hasVersion; }
    public com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Version getVersion() { return version_; }
    
    // required int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // repeated .com.socrata.balboa.PBMetric metrics = 4;
    public static final int METRICS_FIELD_NUMBER = 4;
    private java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric> metrics_ =
      java.util.Collections.emptyList();
    public java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric> getMetricsList() {
      return metrics_;
    }
    public int getMetricsCount() { return metrics_.size(); }
    public com.socrata.balboa.metrics.impl.MessageProtos.PBMetric getMetrics(int index) {
      return metrics_.get(index);
    }
    
    private void initFields() {
      version_ = com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Version.V1_0;
    }
    public final boolean isInitialized() {
      if (!hasEntityId) return false;
      if (!hasVersion) return false;
      if (!hasTimestamp) return false;
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMetric element : getMetricsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasEntityId()) {
        output.writeString(1, getEntityId());
      }
      if (hasVersion()) {
        output.writeEnum(2, getVersion().getNumber());
      }
      if (hasTimestamp()) {
        output.writeInt64(3, getTimestamp());
      }
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMetric element : getMetricsList()) {
        output.writeMessage(4, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasEntityId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getEntityId());
      }
      if (hasVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, getVersion().getNumber());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, getTimestamp());
      }
      for (com.socrata.balboa.metrics.impl.MessageProtos.PBMetric element : getMetricsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socrata.balboa.metrics.impl.MessageProtos.PBMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.socrata.balboa.metrics.impl.MessageProtos.PBMessage result;
      
      // Construct using com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.socrata.balboa.metrics.impl.MessageProtos.PBMessage();
        return builder;
      }
      
      protected com.socrata.balboa.metrics.impl.MessageProtos.PBMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.socrata.balboa.metrics.impl.MessageProtos.PBMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.getDescriptor();
      }
      
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMessage getDefaultInstanceForType() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.socrata.balboa.metrics.impl.MessageProtos.PBMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.metrics_ != java.util.Collections.EMPTY_LIST) {
          result.metrics_ =
            java.util.Collections.unmodifiableList(result.metrics_);
        }
        com.socrata.balboa.metrics.impl.MessageProtos.PBMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socrata.balboa.metrics.impl.MessageProtos.PBMessage) {
          return mergeFrom((com.socrata.balboa.metrics.impl.MessageProtos.PBMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socrata.balboa.metrics.impl.MessageProtos.PBMessage other) {
        if (other == com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.getDefaultInstance()) return this;
        if (other.hasEntityId()) {
          setEntityId(other.getEntityId());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.metrics_.isEmpty()) {
          if (result.metrics_.isEmpty()) {
            result.metrics_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric>();
          }
          result.metrics_.addAll(other.metrics_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setEntityId(input.readString());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Version value = com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Version.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                setVersion(value);
              }
              break;
            }
            case 24: {
              setTimestamp(input.readInt64());
              break;
            }
            case 34: {
              com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Builder subBuilder = com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMetrics(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string entity_id = 1;
      public boolean hasEntityId() {
        return result.hasEntityId();
      }
      public java.lang.String getEntityId() {
        return result.getEntityId();
      }
      public Builder setEntityId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEntityId = true;
        result.entityId_ = value;
        return this;
      }
      public Builder clearEntityId() {
        result.hasEntityId = false;
        result.entityId_ = getDefaultInstance().getEntityId();
        return this;
      }
      
      // required .com.socrata.balboa.PBMessage.Version version = 2;
      public boolean hasVersion() {
        return result.hasVersion();
      }
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Version getVersion() {
        return result.getVersion();
      }
      public Builder setVersion(com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Version value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasVersion = true;
        result.version_ = value;
        return this;
      }
      public Builder clearVersion() {
        result.hasVersion = false;
        result.version_ = com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Version.V1_0;
        return this;
      }
      
      // required int64 timestamp = 3;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // repeated .com.socrata.balboa.PBMetric metrics = 4;
      public java.util.List<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric> getMetricsList() {
        return java.util.Collections.unmodifiableList(result.metrics_);
      }
      public int getMetricsCount() {
        return result.getMetricsCount();
      }
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetric getMetrics(int index) {
        return result.getMetrics(index);
      }
      public Builder setMetrics(int index, com.socrata.balboa.metrics.impl.MessageProtos.PBMetric value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.metrics_.set(index, value);
        return this;
      }
      public Builder setMetrics(int index, com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Builder builderForValue) {
        result.metrics_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMetrics(com.socrata.balboa.metrics.impl.MessageProtos.PBMetric value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.metrics_.isEmpty()) {
          result.metrics_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric>();
        }
        result.metrics_.add(value);
        return this;
      }
      public Builder addMetrics(com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Builder builderForValue) {
        if (result.metrics_.isEmpty()) {
          result.metrics_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric>();
        }
        result.metrics_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMetrics(
          java.lang.Iterable<? extends com.socrata.balboa.metrics.impl.MessageProtos.PBMetric> values) {
        if (result.metrics_.isEmpty()) {
          result.metrics_ = new java.util.ArrayList<com.socrata.balboa.metrics.impl.MessageProtos.PBMetric>();
        }
        super.addAll(values, result.metrics_);
        return this;
      }
      public Builder clearMetrics() {
        result.metrics_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socrata.balboa.PBMessage)
    }
    
    static {
      defaultInstance = new PBMessage(true);
      com.socrata.balboa.metrics.impl.MessageProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socrata.balboa.PBMessage)
  }
  
  public static final class PBMetric extends
      com.google.protobuf.GeneratedMessage {
    // Use PBMetric.newBuilder() to construct.
    private PBMetric() {
      initFields();
    }
    private PBMetric(boolean noInit) {}
    
    private static final PBMetric defaultInstance;
    public static PBMetric getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBMetric getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socrata.balboa.metrics.impl.MessageProtos.internal_static_com_socrata_balboa_PBMetric_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socrata.balboa.metrics.impl.MessageProtos.internal_static_com_socrata_balboa_PBMetric_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      AGGREGATE(0, 0),
      ABSOLUTE(1, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return AGGREGATE;
          case 1: return ABSOLUTE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        AGGREGATE, ABSOLUTE, 
      };
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.socrata.balboa.metrics.impl.MessageProtos.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:com.socrata.balboa.PBMetric.Type)
    }
    
    // required .com.socrata.balboa.PBMetric.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Type type_;
    public boolean hasType() { return hasType; }
    public com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Type getType() { return type_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required .com.socrata.balboa.PBNumber value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private boolean hasValue;
    private com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber value_;
    public boolean hasValue() { return hasValue; }
    public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber getValue() { return value_; }
    
    private void initFields() {
      type_ = com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Type.AGGREGATE;
      value_ = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasType) return false;
      if (!hasName) return false;
      if (!hasValue) return false;
      if (!getValue().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasValue()) {
        output.writeMessage(3, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetric parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetric parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetric parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetric parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetric parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetric parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetric parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetric parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetric parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socrata.balboa.metrics.impl.MessageProtos.PBMetric parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socrata.balboa.metrics.impl.MessageProtos.PBMetric prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.socrata.balboa.metrics.impl.MessageProtos.PBMetric result;
      
      // Construct using com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.socrata.balboa.metrics.impl.MessageProtos.PBMetric();
        return builder;
      }
      
      protected com.socrata.balboa.metrics.impl.MessageProtos.PBMetric internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.socrata.balboa.metrics.impl.MessageProtos.PBMetric();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.getDescriptor();
      }
      
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetric getDefaultInstanceForType() {
        return com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetric build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.socrata.balboa.metrics.impl.MessageProtos.PBMetric buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetric buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.socrata.balboa.metrics.impl.MessageProtos.PBMetric returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socrata.balboa.metrics.impl.MessageProtos.PBMetric) {
          return mergeFrom((com.socrata.balboa.metrics.impl.MessageProtos.PBMetric)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socrata.balboa.metrics.impl.MessageProtos.PBMetric other) {
        if (other == com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Type value = com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 26: {
              com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.Builder subBuilder = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.newBuilder();
              if (hasValue()) {
                subBuilder.mergeFrom(getValue());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setValue(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .com.socrata.balboa.PBMetric.Type type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Type getType() {
        return result.getType();
      }
      public Builder setType(com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Type.AGGREGATE;
        return this;
      }
      
      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // required .com.socrata.balboa.PBNumber value = 3;
      public boolean hasValue() {
        return result.hasValue();
      }
      public com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber getValue() {
        return result.getValue();
      }
      public Builder setValue(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder setValue(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.Builder builderForValue) {
        result.hasValue = true;
        result.value_ = builderForValue.build();
        return this;
      }
      public Builder mergeValue(com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber value) {
        if (result.hasValue() &&
            result.value_ != com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.getDefaultInstance()) {
          result.value_ =
            com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.newBuilder(result.value_).mergeFrom(value).buildPartial();
        } else {
          result.value_ = value;
        }
        result.hasValue = true;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.PBNumber.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socrata.balboa.PBMetric)
    }
    
    static {
      defaultInstance = new PBMetric(true);
      com.socrata.balboa.metrics.impl.MessageProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socrata.balboa.PBMetric)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socrata_balboa_PBMessages_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socrata_balboa_PBMessages_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socrata_balboa_PBMetricsSeries_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socrata_balboa_PBMetricsSeries_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socrata_balboa_PBMetrics_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socrata_balboa_PBMetrics_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socrata_balboa_PBMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socrata_balboa_PBMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socrata_balboa_PBMetric_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socrata_balboa_PBMetric_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\022com.socrata.balboa\032\rnum" +
      "bers.proto\"=\n\nPBMessages\022/\n\010messages\030\001 \003" +
      "(\0132\035.com.socrata.balboa.PBMessage\"@\n\017PBM" +
      "etricsSeries\022-\n\006series\030\001 \003(\0132\035.com.socra" +
      "ta.balboa.PBMetrics\"M\n\tPBMetrics\022-\n\007metr" +
      "ics\030\001 \003(\0132\034.com.socrata.balboa.PBMetric\022" +
      "\021\n\ttimestamp\030\002 \001(\003\"\255\001\n\tPBMessage\022\021\n\tenti" +
      "ty_id\030\001 \002(\t\0226\n\007version\030\002 \002(\0162%.com.socra" +
      "ta.balboa.PBMessage.Version\022\021\n\ttimestamp" +
      "\030\003 \002(\003\022-\n\007metrics\030\004 \003(\0132\034.com.socrata.ba",
      "lboa.PBMetric\"\023\n\007Version\022\010\n\004V1_0\020\000\"\233\001\n\010P" +
      "BMetric\022/\n\004type\030\001 \002(\0162!.com.socrata.balb" +
      "oa.PBMetric.Type\022\014\n\004name\030\002 \002(\t\022+\n\005value\030" +
      "\003 \002(\0132\034.com.socrata.balboa.PBNumber\"#\n\004T" +
      "ype\022\r\n\tAGGREGATE\020\000\022\014\n\010ABSOLUTE\020\001B0\n\037com." +
      "socrata.balboa.metrics.implB\rMessageProt" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_socrata_balboa_PBMessages_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_socrata_balboa_PBMessages_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socrata_balboa_PBMessages_descriptor,
              new java.lang.String[] { "Messages", },
              com.socrata.balboa.metrics.impl.MessageProtos.PBMessages.class,
              com.socrata.balboa.metrics.impl.MessageProtos.PBMessages.Builder.class);
          internal_static_com_socrata_balboa_PBMetricsSeries_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_socrata_balboa_PBMetricsSeries_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socrata_balboa_PBMetricsSeries_descriptor,
              new java.lang.String[] { "Series", },
              com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries.class,
              com.socrata.balboa.metrics.impl.MessageProtos.PBMetricsSeries.Builder.class);
          internal_static_com_socrata_balboa_PBMetrics_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_socrata_balboa_PBMetrics_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socrata_balboa_PBMetrics_descriptor,
              new java.lang.String[] { "Metrics", "Timestamp", },
              com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics.class,
              com.socrata.balboa.metrics.impl.MessageProtos.PBMetrics.Builder.class);
          internal_static_com_socrata_balboa_PBMessage_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_socrata_balboa_PBMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socrata_balboa_PBMessage_descriptor,
              new java.lang.String[] { "EntityId", "Version", "Timestamp", "Metrics", },
              com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.class,
              com.socrata.balboa.metrics.impl.MessageProtos.PBMessage.Builder.class);
          internal_static_com_socrata_balboa_PBMetric_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_socrata_balboa_PBMetric_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socrata_balboa_PBMetric_descriptor,
              new java.lang.String[] { "Type", "Name", "Value", },
              com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.class,
              com.socrata.balboa.metrics.impl.MessageProtos.PBMetric.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.socrata.balboa.metrics.measurements.serialization.impl.NumbersProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
