#!/bin/sh

set -ev

# Parse Jinja2 templates and replace them with configurations.
/bin/env_parse ${BALBOA_CONFIG}.j2
/bin/env_parse ${BALBOA_LOG4J}.j2

exec sudo -u socrata java \
  -Xmx${JAVA_XMX} \
  -Xms${JAVA_XMX} \
  -Dbalboa.config="$BALBOA_CONFIG" \
  -Dlog4j.configuration="$BALBOA_LOG4J" \
  -jar "$JAR" "$THREADS" "$ACTIVEMQ_CONNECTION_STRING" "$ACTIVEMQ_QUEUE"
