#!/bin/sh

set -ev

# Parse Jinja2 templates and replace them with configurations.
/bin/env_parse ${BALBOA_CONFIG}.j2
/bin/env_parse ${BALBOA_LOG4J}.j2

exec sudo -u socrata java \
  -Dcom.sun.management.jmxremote.port=$JMX_PORT \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Dcom.sun.management.jmxremote.rmi.port=$JMX_PORT \
  -Dbalboa.config="$BALBOA_CONFIG" \
  -Dlog4j.configuration="$BALBOA_LOG4J" \
  -jar "$JAR" "$THREADS" "$ACTIVEMQ_CONNECTION_STRING" "$ACTIVEMQ_QUEUE"
